#!/bin/bash

# Script to check and request BigQuery partition modification quota increase

PROJECT_ID="gen-lang-client-0299056258"

echo "=========================================="
echo "BigQuery Partition Modification Quota"
echo "=========================================="
echo ""
echo "Current Limit: 5,000 per day per table"
echo ""
echo "To check quota usage:"
echo "1. Open GCP Console:"
echo "   https://console.cloud.google.com/iam-admin/quotas?project=${PROJECT_ID}"
echo ""
echo "2. Search for: 'partition modifications'"
echo ""
echo "3. Look for:"
echo "   - bigquery.googleapis.com/partition_modifications_per_column_partitioned_table"
echo ""
echo "=========================================="
echo "To Request Quota Increase:"
echo "=========================================="
echo ""
echo "Option 1: Via GCP Console (Recommended)"
echo "--------------------------------------"
echo "1. Go to: https://console.cloud.google.com/iam-admin/quotas?project=${PROJECT_ID}"
echo "2. Search: 'partition modifications'"
echo "3. Select the quota"
echo "4. Click 'EDIT QUOTAS'"
echo "5. Request: 20,000 or 50,000 per day"
echo "6. Submit request (usually approved within hours)"
echo ""
echo "Option 2: Via gcloud (if you have permissions)"
echo "----------------------------------------------"
echo "gcloud alpha services quota update \\"
echo "  --service=bigquery.googleapis.com \\"
echo "  --consumer=projects/${PROJECT_ID} \\"
echo "  --metric=bigquery.googleapis.com/partition_modifications_per_column_partitioned_table \\"
echo "  --value=20000"
echo ""
echo "=========================================="
echo "Current Status:"
echo "=========================================="
echo "✅ Job deployed with conservative settings:"
echo "   - 30 second delays between uploads"
echo "   - 50K row chunks for large wallets"
echo "   - 100 wallets per batch"
echo ""
echo "⚠️  If quota is exhausted, wait ~24 hours for reset"
echo "   or request quota increase above"
echo ""
