FROM python:3.9-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy heuristics model and script
COPY combined_heuristics_model.json .
COPY classify-markets-bigquery.py .

# Run script
CMD ["python", "-u", "classify-markets-bigquery.py"]
